apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDenyIngressDelete
metadata:
  name: K8sDenyIngressDelete
spec:
  match:
    kinds:
      - apiGroups: ["ingress"]
        kinds: ["Ingress"]
  parameters:
    ingress: "test"