apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDenyIngressDelete
metadata:
  name: k8sdenyingressdelete
spec:
  match:
    kinds:
      - apiGroups: ["*"]
        kinds: ["Ingress"]
  parameters:
    ingress: "test"